config/routes.rb
Rails.application.routes.draw do

  root to: 'static_page#top'
  get 'privacy_policy', to: 'static_page#privacy'
  get 'disclaimer', to: 'static_page#disclaimer'
  get 'lp', to: 'static_page#landingpage'

  devise_for :users

  resources :users, only: :update
  get '/users/:nickname' => 'users#show', as: :users_show
  get '/users/:nickname/edit' => 'users#edit', as: :users_edit
  get '/users/:nickname/record' => 'users#record', as: :users_record do
    collection do
      get 'search'
    end
  end
  get '/users/:nickname/post' => 'users#post', as: :users_post
  get '/users/:nickname/post_draft' => 'users#post_draft', as: :users_post_draft
  get '/users/:nickname/records' => 'users#records', as: :users_records
  get '/users/:nickname/search' => 'users#search', as: :users_search
  get '/users/:nickname/followings' => 'relationships#followings', as: 'followings'
  get '/users/:nickname/followers' => 'relationships#followers', as: 'followers' 
  resources :relationships, only: [:create, :destroy]

  resources :records do
    resources :comment_records
    collection do
      get 'search'
    end
  end

  resources :posts do
    resources :comment_posts
  end
  post 'posts/attach', to: 'posts#attach'
  
  resources :advertisements
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :nickname, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }

  has_many :records, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comment_records, dependent: :destroy
  has_many :comment_posts, dependent: :destroy

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def to_param
    return self.nickname
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, except: [:update]
  before_action :move_to_show, only: [:edit, :records, :post_draft, :search]
  before_action :set_q, only: [:records, :search]

  def edit
    
  end

  def update
    if current_user.update(user_params)
    else
      render :edit
    end
  end

  def show
    @records = Record.where(user_id: @user.id).includes(:user).order(date: "DESC").order(hour_id: "DESC").order("created_at DESC").limit(4)
    @posts = Post.where(user_id: @user.id).includes(:user).where(status_id: 2).order("created_at DESC").limit(4)
    @users_records = Record.where(user_id: @user.id)
    
    if @users_records.count > 0
      # 全体
        # 資金推移
      @users_records_order_date = @users_records.order(:date)
      @sum_price = []
      sum = 0
      @users_records_order_date.each do |record|
        sum = sum + record.price_renge
        date = record.date
        data = [date, sum]
        @sum_price << data
      end

        # 勝率
      @win_count = @users_records.where('price_renge > ?', 0).count
      @lose_count = @users_records.where('price_renge < ?', 0).count
      @rate = {"lose": @lose_count, "win": @win_count}

        # PF
      @profit = @users_records.where('price_renge > ?', 0).pluck(:price_renge).sum
      @loss = @users_records.where('price_renge < ?', 0).pluck(:price_renge).sum
      @pf = @profit / (@loss * -1)

        # 通貨ペア別勝率
      @users_records_pairs = @users_records.group(:pair_id).pluck(:pair_id)

        # 取引結果
      @users_records_result_section = Record.where(user_id: @user.id).group(:result_section_id).pluck(:result_section_id)
      @result_graph = []
      @users_records_result_section.each do |result_id|
        result_section_name = ResultSection.find(result_id).name
        result_section_count = Record.where(user_id: @user.id).where(result_section_id: result_id).count
        result_data = [result_section_name, result_section_count]
        @result_graph << result_data
      end
    end

    # 今年
    now_year = Time.now.year
    @one_year = Record.where('extract(year from date) = ?', now_year)

    # 今月
    now_month = Time.now.month
    @one_month = Record.where('extract(month from date) = ?', now_month)

    @users_records_month = @users_records.where('extract(year from date) = ?', now_year).where('extract(month from date) = ?', now_month)
    @users_records_month_order_date = @users_records_month.order(:date)

    if @users_records_month.count > 0
        # 資金推移
      @users_records_month_order_date = @users_records_month.order(:date)
      @sum_price_month = []
      sum_month = 0
      @users_records_month_order_date.each do |record|
        sum_month = sum_month + record.price_renge
        date_month = record.date
        data_month = [date_month, sum_month]
        @sum_price_month << data_month
      end

        # 勝率
      @win_count_month = @users_records_month.where('price_renge > ?', 0).count
      @lose_count_month = @users_records_month.where('price_renge < ?', 0).count
      @rate_month = {"lose": @lose_count_month, "win": @win_count_month}

        # PF
      @profit_month = @users_records_month.where('price_renge > ?', 0).pluck(:price_renge).sum
      @loss_month = @users_records_month.where('price_renge < ?', 0).pluck(:price_renge).sum
      @pf_month = @profit_month / (@loss_month * -1)

        # 通貨ペア別勝率
      @users_records_pairs_month = @users_records_month.group(:pair_id).pluck(:pair_id)

        # 通貨ペア別PF
      @users_records_result_section_month = Record.where(user_id: @user.id).where('extract(year from date) = ?', now_year).where('extract(month from date) = ?', now_month).group(:result_section_id).pluck(:result_section_id)
      @result_graph_month = []
      @users_records_result_section_month.each do |result_month_id|
        result_section_month_name = ResultSection.find(result_month_id).name
        result_section_month_count = Record.where(user_id: @user.id).where('extract(year from date) = ?', now_year).where('extract(month from date) = ?', now_month).where(result_section_id: result_month_id).count
        result_month_data = [result_section_month_name, result_section_month_count]
        @result_graph_month << result_month_data
      end
    end
  end

  def record
    @records = Record.where(user_id: @user.id).includes(:user).order(date: "DESC").order(hour_id: "DESC").order("created_at DESC").page(params[:page]).per(16)
  end

  def post
    @posts = Post.where(user_id: @user.id).includes(:user).where(status_id: 2).order("created_at DESC").page(params[:page]).per(20)
  end

  def post_draft
    @posts = Post.where(user_id: @user.id).includes(:user).where(status_id: 1).order("created_at DESC").page(params[:page]).per(20)
  end

  def records
    @records = Record.where(user_id: @user.id).includes(:user).order(date: "DESC").order(hour_id: "DESC").order("created_at DESC").page(params[:page]).per(50)
  end

  def search
    @results = @q.result.where(user_id: @user.id).includes(:user).order(date: "DESC").order("created_at DESC").page(params[:page]).per(50)
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end

  def set_user
    @user = User.find_by(nickname: params[:nickname])
  end

  def move_to_show
    unless user_signed_in? && current_user.nickname == @user.nickname
      redirect_to action: :show
    end
  end

  def set_q
    @q = Record.ransack(params[:q])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% breadcrumb :user_edit %>

<div class="content">
  <div class="container">
    <h1>登録情報の変更</h1>
    
    <%= form_with model: current_user, local: true do |f|%>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>
      
      <div class="field">
        <%= f.label :nickname %> <br />
        <%= f.text_field :nickname, autofocus: true %>
      </div>

      <div class="actions">
        <%= f.submit "Update", data: { confirm: "メールアドレスを変更した場合はメールをご確認のうえ認証手続きを進めてください" }%>
      </div>
    <% end %>
    <h2>パスワードの変更に関して</h2>
    <p><b>以下の手順で進めてください</b></p>
    <ul class="number">
      <li>ログアウト</li>
      <li>ログインページを表示</li>
      <li>パスワードの再設定を選択</li>
    </ul>
  </div>
</div>
<div class="space"></div>

app/views/users/post.html.erb
<% breadcrumb :user_posts %>

<div class="content">
<h1><%= @user.nickname %>記事一覧</h1>
<div class="post_grid">
  <% @posts.each do |post| %>
    <%= render partial: "shared/index_post", locals: { post: post } %>
  <% end %>
</div>
  <%= paginate @posts %>

</div>
<div class="space"></div>

app/views/users/post_draft.html.erb
<% breadcrumb :user_posts_draft %>

<div class="content">
<h1><%= @user.nickname %>さんの下書き記事一覧</h1>
<div class="post_grid">
  <% @posts.each do |post| %>
    <%= render partial: "shared/index_post", locals: { post: post } %>
  <% end %>
</div>
  <%= paginate @posts %>

</div>
<div class="space"></div>

app/views/users/record.html.erb
<% breadcrumb :user_record %>

<div class="content">
  <h1><%= @user.nickname %>さんのトレードノート</h1>
  <div class="grid">
    <% @records.each do |record| %>
      <%= render partial: "shared/index_record", locals: { record: record } %>
    <% end %>
  </div>
  <%= paginate @records %>
</div>
<div class="space"></div>

app/views/users/records.html.erb
<% breadcrumb :user_records %>

<div class="content">
  <h1><%= @user.nickname %>さんの取引履歴</h1>
  <div class="container">
    <%= search_form_for @q, url: users_search_path do |f| %>
      <div class="search_date">
        <div>
          <%= f.date_field :created_at_gteq %>
        </div>
        <div>
          <p>　　〜　　</p>
        </div>
        <div>
          <%= f.date_field :created_at_lteq_end_of_day %>
        </div>
      </div>
      <%= f.collection_select :pair_id_eq,Pair.all,:id,:name,include_blank: '通貨ペアで検索' %>
      <%= f.collection_select :hour_id_eq,Hour.all,:id,:name,include_blank: '取引時間帯で検索' %>
      <%= f.collection_select :ashi_id_eq,Ashi.all,:id,:name,include_blank: '時間足で検索' %>
      <%= f.collection_select :indi_main_id_eq,IndiMain.all,:id,:name,include_blank: 'インジケーターで検索' %>
      <%= f.collection_select :line_main_id_eq,LineMain.all,:id,:name,include_blank: 'ラインで検索' %>
      <%= f.collection_select :kind_id_eq,Kind.all,:id,:name,include_blank: 'トレード種別で検索' %>
      <%= f.collection_select :result_section_id_eq,ResultSection.all,:id,:name,include_blank: '理由で検索' %>
      <%= f.submit '検索' %>
    <% end %>
  </div>
  <table>
    <% @records.each do |record| %>
    <tr>
      <th class="date"><%= record.date %>(<%= record.hour.name %>時)</th>
      <td class="records_content"><%= link_to record.pair.name, record_path(record.id), class: "link_word" %></td>
      <td class="records_content"><%= record.result_section.name %></td>
    </tr>
    <% end %>
  </table>
  <%= paginate @records %>
</div>

<div class="space"></div>

app/views/users/search.html.erb
<div class="content">
  <h1><%= @user.nickname %>さんの取引履歴</h1>
  <div class="container">
    <%= search_form_for @q, url: users_search_path do |f| %>
      <div class="search_date">
        <div>
          <%= f.date_field :created_at_gteq %>
        </div>
        <div>
          <p>　　〜　　</p>
        </div>
        <div>
          <%= f.date_field :created_at_lteq_end_of_day %>
        </div>
      </div>
      <%= f.collection_select :pair_id_eq,Pair.all,:id,:name,include_blank: '通貨ペアで検索' %>
      <%= f.collection_select :hour_id_eq,Hour.all,:id,:name,include_blank: '取引時間帯で検索' %>
      <%= f.collection_select :ashi_id_eq,Ashi.all,:id,:name,include_blank: '時間足で検索' %>
      <%= f.collection_select :indi_main_id_eq,IndiMain.all,:id,:name,include_blank: 'インジケーターで検索' %>
      <%= f.collection_select :line_main_id_eq,LineMain.all,:id,:name,include_blank: 'ラインで検索' %>
      <%= f.collection_select :kind_id_eq,Kind.all,:id,:name,include_blank: 'トレード種別で検索' %>
      <%= f.collection_select :result_section_id_eq,ResultSection.all,:id,:name,include_blank: '理由で検索' %>
      <%= f.submit '検索' %>
    <% end %>
  </div>
  <table>
    <% @results.each do |record| %>
    <tr>
      <th class="date"><%= record.date %>(<%= record.hour.name %>時)</th>
      <td class="records_content"><%= link_to record.pair.name, record_path(record.id), class: "link_word" %></td>
      <td class="records_content"><%= record.result_section.name %></td>
    </tr>
    <% end %>
  </table>
  <%= paginate @results %>
</div>

<div class="space"></div>

app/views/users/show.html.erb
<% set_meta_tags title: "#{@user.nickname}さんのページ", description: "#{@user.nickname}さんのトレードノートを元に取引分析をしているページです。" %>

<% breadcrumb :user_show %>

<div class="content">
  <h1><%= @user.nickname %>さんのページ</h1>
  <%= render partial: "shared/ad_xm" %>
  <%= render partial: "relationships/relationship_btn", locals: { user: @user } %>

  <div class="container">
    <h2>プロフィール</h2>
    <p>name: <b class="highlight"><%= @user.nickname %></b></p>
    <div class="space"></div>
    <div class="btns">
      <%= link_to "フォロー : #{@user.followings.count}", "/users/#{ @user.nickname }/followings", class: "btn" %>
      <%= link_to "フォロワー : #{@user.followers.count}", "/users/#{ @user.nickname }/followers", class: "btn" %>
    </div>
    <div class="space"></div>
      <ul>
        <li>TradeNote数: <%= link_to @user.records.count, users_record_path, class: "link_word" %></li>
        <li>投稿記事数: <%= link_to @user.posts.count, users_post_path, class: "link_word" %></li>
      </ul>
  </div>

  <h2><%= @user.nickname %>さんの取引分析</h2>

  <% if @users_records.count > 0 %>

    <% if user_signed_in? && current_user.nickname == @user.nickname %>
      <h3>資金推移</h3>
      <p class="highlight">資金推移は<%= @user.nickname %>さんのみに表示されます</p>
      <h4>取引期間全体</h4>
      <%= line_chart @sum_price, xtitle: "date", ytitle: "price"   %>
      <div class="space"></div>
      <%= column_chart @users_records_order_date.group(:date).sum(:price_renge), xtitle: "date", ytitle: "price" %>
      <% if @users_records_month.count > 0 %>
      <h4>今月</h4>
      <%= line_chart @sum_price_month, xtitle: "date", ytitle: "price" %>
      <div class="space"></div>
      <%= column_chart @users_records_month_order_date.group(:date).sum(:price_renge), xtitle: "date", ytitle: "price" %>
      <% else %>
        <div class="pair_graph">
          <h4>今月</h4>
          <p>今月のトレードノートはありません</p>
        </div>
      <% end %>
    <% end %>

    <%= render partial: "shared/ad_xm" %>

    <h3>勝率/PF</h3>
    <div class="pair_rate">
      <div class="pair_graph">
        <h4>全体</h4>
        <%= pie_chart @rate %>
        <div>
          <% if @profit == 0 || @loss == 0 %>
            <p class="data_info">PF : 未判定</p>
          <% else %>
            <p class="data_info">PF : <%= @pf.floor(2) %></p>
          <% end %>
        </div>
      </div>
      <% if @users_records_month.count > 0 %>
        <div class="pair_graph">
          <h4>今月</h4>
          <%= pie_chart @rate_month %>
          <div>
            <% if @profit_month == 0 || @loss_month == 0 %>
              <p class="data_info">PF : 未判定</p>
            <% else %>
              <p class="data_info">PF : <%= @pf_month.floor(2) %></p>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="pair_graph">
          <h4>今月</h4>
          <p>今月のトレードノートはありません</p>
        </div>
      <% end %>
    </div>
    
    <h3>通貨ペア別勝率/PF</h3>
    <h4>全体</h4>
    <div class="pair_rate">
      <% @users_records_pairs.each do |pair| %>
        <%# 計算事項 %>
            <%# ペアの名前 %>
            <% pair_name = Pair.find(pair).name%>
            <%# 勝率計算 %>
            <% win_count_pair = @users_records.where(pair_id: pair).where('price_renge > ?', 0).count %>
            <% lose_count_pair = @users_records.where(pair_id: pair).where('price_renge < ?', 0).count %>
            <% rate_pair = {"lose": lose_count_pair, "win": win_count_pair} %>
            <%# PF計算 %>
            <% profit_pair = @users_records.where(pair_id: pair).where('price_renge > ?', 0).pluck(:price_renge).sum %>
            <% loss_pair = @users_records.where(pair_id: pair).where('price_renge < ?', 0).pluck(:price_renge).sum %>
            <% pf_pair = profit_pair / (loss_pair * -1) %>
        <%# ここまで %>
        <div>
          <p class="data_info"><%= pair_name %></p>
          <div class="pair_graph">
            <%= pie_chart rate_pair %>
            <div>
              <% if profit_pair == 0 || loss_pair == 0 %>
                <p class="data_info">PF : 未判定</p>
              <% else %>
                <p class="data_info">PF : <%= pf_pair.floor(2) %></p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="space"></div>

    <% if @users_records_month.count > 0 %>
      <h4>今月</h4>
      <div class="pair_rate">
        <% @users_records_pairs_month.each do |pair| %>
          <%# 計算事項 %>
              <%# ペアの名前 %>
              <% pair_name_month = Pair.find(pair).name%>
              <%# 勝率計算 %>
              <% win_count_pair_month = @users_records_month.where(pair_id: pair).where('price_renge > ?', 0).count %>
              <% lose_count_pair_month = @users_records_month.where(pair_id: pair).where('price_renge < ?', 0).count %>
              <% rate_pair_month = {"lose": lose_count_pair_month, "win": win_count_pair_month} %>
              <%# PF計算 %>
              <% profit_pair_month = @users_records_month.where(pair_id: pair).where('price_renge > ?', 0).pluck(:price_renge).sum %>
              <% loss_pair_month = @users_records_month.where(pair_id: pair).where('price_renge < ?', 0).pluck(:price_renge).sum %>
              <% pf_pair_month = profit_pair_month / (loss_pair_month * -1) %>
          <%# ここまで %>
          <div>
            <p class="data_info"><%= pair_name_month %></p>
            <div class="pair_graph">
              <%= pie_chart rate_pair_month %>
              <div>
                <% if profit_pair_month == 0 || loss_pair_month == 0 %>
                  <p class="data_info">PF : 未判定</p>
                <% else %>
                  <p class="data_info">PF : <%= pf_pair_month.floor(2) %></p>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <h4>今月</h4>
      <p>今月のトレードノートはありません</p>
    <% end %>

    <h3>取引結果分析</h3>
    <h4>全体</h4>
    <%= bar_chart @result_graph,  xtitle: "count", points: false, height: "500px" %>
    <% if @users_records_month.count > 0 %>
      <h4>今月</h4>
      <%= bar_chart @result_graph_month,  xtitle: "count", points: false, height: "500px" %>
    <% else %>
      <div class="pair_graph">
        <h4>今月</h4>
        <p>今月のトレードノートはありません</p>
      </div>
    <% end %>

  <% else %>

    <p>トレードノートを作成してください<p>

  <% end %>

  <div class="space"></div>
  
  <h2><%= @user.nickname %>さんのトレードノート</h2>
  <div class="grid">
    <% @records.each do |record| %>
      <%= render partial: "shared/index_record", locals: { record: record } %>
    <% end %>
  </div>
  <div class="space"></div>
  <p><%= link_to 'もっと見る', users_record_path, class: "link_word" %></p>
  
  <div class="space"></div>

  <h2><%= @user.nickname %>さんの記事</h2>
  <div class="post_grid">
    <% @posts.each do |post| %>
      <%= render partial: "shared/index_post", locals: { post: post } %>
    <% end %>
  </div>
  <div class="space"></div>
  <p><%= link_to 'もっと見る', users_post_path, class: "link_word" %></p>
  
  <div class="space"></div>
  
  <% if user_signed_in? && current_user.nickname == @user.nickname %>
    <div class="container">
      <h2><%= @user.nickname %>さんの専用エリア</h2>
      <div class="btns">
        <%= link_to 'ユーザー情報の編集', users_edit_path(current_user.nickname), class: 'btn' %>
        <%= link_to "取引履歴を一覧形式で見る", users_records_path, class: "btn" %>
        <%= link_to "下書き記事をみる", users_post_draft_path, class: "btn" %>
      </div>
    </div>

    <div class="space"></div>
  <% end %>

</div>

app/views/users/update.html.erb
<div class="space"></div>

<div class="content">
  <div class="container">
    <h1>登録情報の更新が完了しました</h1>
    <p>
    メールをご確認のうえ認証手続きをお願いいたします。<br>
    迷惑メールフォルダに振り分けられている可能性があります。
    </p>
    <div class="space"></div>
    <%= link_to "マイページ", "/users/#{current_user.nickname}", class: "btn" %>
    <div class="space"></div>
  </div>
</div>

<div class="space"></div>