config/routes.rb
Rails.application.routes.draw do

  root to: 'static_page#top'
  get 'privacy_policy', to: 'static_page#privacy'
  get 'disclaimer', to: 'static_page#disclaimer'
  get 'lp', to: 'static_page#landingpage'

  devise_for :users

  resources :users, only: :update
  get '/users/:nickname' => 'users#show', as: :users_show
  get '/users/:nickname/edit' => 'users#edit', as: :users_edit
  get '/users/:nickname/record' => 'users#record', as: :users_record do
    collection do
      get 'search'
    end
  end
  get '/users/:nickname/post' => 'users#post', as: :users_post
  get '/users/:nickname/post_draft' => 'users#post_draft', as: :users_post_draft
  get '/users/:nickname/records' => 'users#records', as: :users_records
  get '/users/:nickname/search' => 'users#search', as: :users_search
  get '/users/:nickname/followings' => 'relationships#followings', as: 'followings'
  get '/users/:nickname/followers' => 'relationships#followers', as: 'followers' 
  resources :relationships, only: [:create, :destroy]

  resources :records do
    resources :comment_records
    collection do
      get 'search'
    end
  end

  resources :posts do
    resources :comment_posts
  end
  post 'posts/attach', to: 'posts#attach'
  
  resources :advertisements
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/record.rb
class Record < ApplicationRecord

  with_options presence: true do
    validates :date
    validates :pair_id
    validates :ashi_id
    validates :price_renge, numericality: true
    validates :entry_basis
    validates :result_section_id
    validates :result_content
  end

  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :pair_id
    validates :ashi_id
    validates :result_section_id
  end

  FILE_NUMBER_LIMIT = 3

  validate :validate_number_of_files

  belongs_to :user
  has_many_attached :images
  has_many :comment_records, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :hour, optional: true
  belongs_to :ashi, optional: true
  belongs_to :pair, optional: true
  belongs_to :kind, optional: true
  belongs_to :line_main, optional: true
  belongs_to :line_sub, optional: true
  belongs_to :indi_main, optional: true
  belongs_to :indi_sub, optional: true
  belongs_to :order, optional: true
  belongs_to :result_section, optional: true

  private

  def validate_number_of_files
    return if images.length <= FILE_NUMBER_LIMIT
    errors.add(:images, "に添付できる画像は#{FILE_NUMBER_LIMIT}件までです。")
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_record, only: [:edit, :update, :show, :destroy]
  before_action :set_ad, only: [:create, :update]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  before_action :set_q, only: [:index, :search]

  def index
    @records = Record.includes(:user).order(date: "DESC").order(hour_id: "DESC").order("created_at DESC").page(params[:page]).per(16)
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    unless @record.save
      render :new
    end
  end

  def edit
    
  end

  def update
    @ad_xm = Advertisement.find(1)
    @ad_titan = Advertisement.find(4)
    @ad_exness = Advertisement.find(5)
    unless @record.update(record_params)
      render action: :edit
    end
  end

  def show
    @comment_record = CommentRecord.new
    @comment_records = @record.comment_records
  end

  def destroy
    @record.destroy
    redirect_to records_path
  end

  def search
    @results = @q.result.order(date: "DESC")
  end

  private

  def record_params
    params.require(:record).permit(:date, :hour_id, :pair_id, :ashi_id, :kind_id,:line_main_id, :line_sub_id, :indi_main_id, :indi_sub_id, :entry_basis, :order_id, :price_renge, :result_section_id, :result_content, images: []).merge(user_id: current_user.id)
  end
  
  def set_record
    @record = Record.find(params[:id])
  end

  def set_ad
    @ad_xm = Advertisement.find(1)
    @ad_titan = Advertisement.find(4)
    @ad_exness = Advertisement.find(5)
  end

  def move_to_index
    unless user_signed_in? && current_user.id == @record.user_id
      redirect_to action: :show
    end
  end

  def set_q
    @q = Record.ransack(params[:q])
  end

end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/create.html.erb
<div class="space"></div>
<div class="content">

  <h1>TradeNoteの作成が完了しました</h1>
  <p>
  TradeNoteを作成していただきありがとうございます。
  </p>

  <div class="container">
    <div class="btns">
      <%= link_to "TradeNote一覧", records_path, class: "btn" %>
      <%= link_to "TradeNote詳細", record_path(@record.id), class: "btn" %>
      <%= link_to "マイページ", "/users/#{current_user.nickname}", class: "btn" %>
      <%= link_to "Top", "/", class: "btn" %>
    </div>
  </div>

  <h2>TradeNote運営おすすめ海外fx会社</h2>
  <div class="ad_create">
    <div>
      <h3>XM</h3>
      <%= link_to image_tag(@ad_xm.img_url), @ad_xm.af_link %>
      <p class="ad_info_create"><%= @ad_xm.content %></p>
    </div>
    <div>
      <h3>Titan Fx</h3>
      <%= link_to image_tag(@ad_titan.img_url), @ad_titan.af_link %>
      <p class="ad_info_create"><%= @ad_titan.content %></p>
    </div>
    <div>
      <h3>EXNESS</h3>
      <%= link_to image_tag(@ad_exness.img_url), @ad_exness.af_link %>
      <p class="ad_info_create"><%= @ad_exness.content %></p>
    </div>
  </div>
</div>
<div class="space"></div>

app/views/records/edit.html.erb
<% breadcrumb :record_edit %>

<div class="content">
  <div class="container">
    <h1>TradeNoteの修正</h1>
    <%= render partial: "shared/form_record", locals: { record: @record } %>
  </div>
</div>
<div class="space"></div>

app/views/records/index.html.erb
<% set_meta_tags title: 'Trade-Noteの一覧', description: '「自分の取引記録が最強の取引教材になるその時まで」。みんなのfx取引記録の一覧が集結！通貨ペア、時間足、トレード種別（スキャルピング、デイトレ...）で検索して参考になる取引を見つけよう！' %>

<% breadcrumb :records_index %>

<div class="content">
  <h1>全てのトレードノート</h1>
  <div class="container">
    <%= search_form_for @q, url: search_records_path do |f| %>
      <div class="search_date">
        <div>
          <%= f.date_field :created_at_gteq %>
        </div>
        <div>
          <p>　　〜　　</p>
        </div>
        <div>
          <%= f.date_field :created_at_lteq_end_of_day %>
        </div>
      </div>
      <%= f.collection_select :pair_id_eq,Pair.all,:id,:name,include_blank: '通貨ペアで検索' %>
      <%= f.collection_select :hour_id_eq,Hour.all,:id,:name,include_blank: '取引時間帯で検索' %>
      <%= f.collection_select :ashi_id_eq,Ashi.all,:id,:name,include_blank: '時間足で検索' %>
      <%= f.collection_select :indi_main_id_eq,IndiMain.all,:id,:name,include_blank: 'インジケーターで検索' %>
      <%= f.collection_select :line_main_id_eq,LineMain.all,:id,:name,include_blank: 'ラインで検索' %>
      <%= f.collection_select :kind_id_eq,Kind.all,:id,:name,include_blank: 'トレード種別で検索' %>
      <%= f.collection_select :result_section_id_eq,ResultSection.all,:id,:name,include_blank: '理由で検索' %>
      <%= f.submit '検索' %>
    <% end %>
  </div>
  <div class="grid">
    <% @records.each do |record| %>
      <%= render partial: "shared/index_record", locals: { record: record } %>
    <% end %>
  </div>
  <%= paginate @records %>
</div>
<div class="space"></div>

app/views/records/new.html.erb
<% breadcrumb :record_new %>

<div class="content">
  <div class="container">
    <h1>新規TradeNoteの作成</h1>
    <%= render partial: "shared/form_record", locals: { record: @record } %>
  </div>
</div>
<div class="space"></div>

app/views/records/search.html.erb
<% breadcrumb :record_search %>

<div class="content">
  <h1>トレードノートの検索結果</h1>
  <div class="container">
    <%= search_form_for @q, url: search_records_path do |f| %>
      <div class="search_date">
        <div>
          <%= f.date_field :created_at_gteq %>
        </div>
        <div>
          <p>　　〜　　<p>
        </div>
        <div>
          <%= f.date_field :created_at_lteq_end_of_day %>
        </div>
      </div>
      <%= f.collection_select :pair_id_eq,Pair.all,:id,:name,include_blank: '通貨ペアで検索' %>
      <%= f.collection_select :hour_id_eq,Hour.all,:id,:name,include_blank: '取引時間帯で検索' %>
      <%= f.collection_select :ashi_id_eq,Ashi.all,:id,:name,include_blank: '時間足で検索' %>
      <%= f.collection_select :indi_main_id_eq,IndiMain.all,:id,:name,include_blank: 'インジケーターで検索' %>
      <%= f.collection_select :line_main_id_eq,LineMain.all,:id,:name,include_blank: 'ラインで検索' %>
      <%= f.collection_select :kind_id_eq,Kind.all,:id,:name,include_blank: 'トレード種別で検索' %>
      <%= f.collection_select :result_section_id_eq,ResultSection.all,:id,:name,include_blank: '理由で検索' %>
      <%= f.submit '検索' %>
    <% end %>

        <%= link_to "一覧に戻る", records_path, class: "link_word" %>

  </div>
  <div class="grid">
    <% @results.each do |record| %>
      <%= render partial: "shared/index_record", locals: { record: record } %>
    <% end %>
  </div>
</div>
  
<div class="space"></div>

app/views/records/show.html.erb
<% if @record.images.attached? %>
  <% set_meta_tags title: "#{@record.pair.name}での取引詳細/#{@record.date}", description: @record.result_content, keywords: "トレードノート, #{@record.pair.name}, fx, 仮想通貨, 株", og:{image: image_url(url_for(@record.images[0]))}, twitter:{image: image_url(url_for(@record.images[0]))} %>
<% else %>
  <% set_meta_tags title: "#{@record.pair.name}での取引詳細/#{@record.date}", description: @record.result_content, keywords: "トレードノート, #{@record.pair.name}, fx, 仮想通貨, 株", og:{image: image_url('top.jpg')} %>
<% end %>

<% breadcrumb :record_show %>

<div class="space"></div>
<div class="content">
  <h1><%= @record.pair.name %>での取引の詳細</h1>
  <div class="record_content">
    <div class="left_content">
      <h2>取引画像</h2>
      <% if @record.images.attached? %>
        <div class="record_images">
          <% @record.images.each do |image| %>
            <%= image_tag image, class: "recorded_img_show" %>
          <%end%>
        </div>
      <% else %>
        <%= image_tag "no_image.jpg", class: "recorded_img_show" %>
      <% end %>
    </div>
    <div class="right_content">
      <h2>取引概要</h2>
      <table class="table">
        <tr>
          <th>取引日時</th>
          <td><%= @record.date %>(<%= @record.hour.name %>時)</td>
        </tr>
        <tr>
          <th>通貨ペア</th>
          <td><%= @record.pair.name %> </td>
        </tr>
        <tr>
          <th>時間足</th>
          <td><%= @record.ashi.name %> </td>
        </tr>
        <% if @record.kind != nil %>
        <tr>
          <th>トレード種別</th>
          <td><%= @record.kind.name %> </td>
        </tr>
        <% end %>
        <% if @record.indi_main != nil %>
          <tr>
            <th>メインインジケーター</th>
            <td><%= @record.indi_main.name %> </td>
          </tr>
        <% end %>
        <% if @record.indi_sub != nil %>
          <tr>
            <th>サブインジケーター</th>
            <td><%= @record.indi_sub.name %> </td>
          </tr>
        <% end %>
        <% if @record.line_main != nil %>
          <tr>
            <th>メインライン</th>
            <td><%= @record.line_main.name %> </td>
          </tr>
        <% end %>
        <% if @record.line_sub != nil %>
          <tr>
            <th>サブライン</th>
            <td><%= @record.line_sub.name %> </td>
          </tr>
        <% end %>
        <% if @record.order != nil %>
          <tr>
            <th>注文方式</th>
            <td><%= @record.order.name %> </td>
          </tr>
        <% end %>
        <% if @record.price_renge > 0 %>
          <tr>
            <th>結果</th>
            <td>利益獲得</td>
          </tr>
        <% elsif @record.price_renge < 0 %>
          <tr>
            <th>結果</th>
            <td>損失</td>
          </tr>
        <% else %>
          <tr>
            <th>獲得値幅</th>
            <td>記録なし</td>
          </tr>
        <% end %>
        <tr>
          <th>取引結果</th>
          <td><%= @record.result_section.name %></td>
        </tr>
        <tr>
          <th>created by</th>
          <td><%= link_to @record.user.nickname, "/users/#{@record.user.nickname}", class: "link_word" %></td>
        </tr>
      </table>
    </div>
  </div>
  <%= render partial: "shared/ad_xm" %>
  <div class="entry_basis">
    <h2>エントリーした根拠</h2>
    <div class="show_content">
      <%= safe_join(@record.entry_basis.split("\n"),tag(:br)) %>
    </div>
  </div>
  <div class="result">
    <h2>今回の取引の総括</h2>
    <div class="show_content">
      <%= safe_join(@record.result_content.split("\n"),tag(:br)) %>
    </div>
  </div>
  <% if user_signed_in? && current_user.id == @record.user_id %>
    <div class="container">
      <h2>投稿者専用エリア</h2>
      <div class="btns">
        <%= link_to '編集', edit_record_path(@record.id), class: 'btn' %>
        <%= link_to '削除', record_path(@record.id), method: :delete, data: { confirm: "削除しますか？" }, class: 'btn' %>
      </div>
    </div>
  <% end %>

  <div class="container">
    <h2>コメント</h2>

    <div>
      <%= react_component "Like" %>
    </div>

    <% if user_signed_in? %>
      <%= form_with model: [@record, @comment_record],url: record_comment_records_path(@record), local: false do |form| %>
        <%= form.text_area :comment, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <div class="btns">
        <%= link_to "新規登録してコメントする", new_user_registration_path, class: "btn" %>
        <%= link_to "ログインしてコメントする", new_user_session_path, class: "btn" %>
      </div>
    <% end %>
    <div>
      <%#<i class="fas fa-eye like-btn"></i>_<%= @record.impressions_count %>
    </div>
    
    <div class="comments">
      <h3>＜コメント一覧＞</h3>
      <div id="comments__area">
        <%= render partial: 'comment_records/index', locals: { comments: @comment_records } %>
      </div>
    </div>
  </div>
</div>
<div class="space"></div>

app/views/records/update.html.erb
<div class="space"></div>
<div class="content">

  <h1>TradeNoteの編集が完了しました</h1>
  <p>
  TradeNoteを編集をしていただきありがとうございます。
  </p>

  <div class="container">
    <div class="btns">
      <%= link_to "TradeNote一覧", records_path, class: "btn" %>
      <%= link_to "TradeNote詳細", record_path(@record.id), class: "btn" %>
      <%= link_to "マイページ", "/users/#{current_user.nickname}", class: "btn" %>
      <%= link_to "Top", "/", class: "btn" %>
    </div>
  </div>

  <h2>TradeNote運営おすすめ海外fx会社</h2>
  <div class="ad_create">
    <div>
      <h3>XM</h3>
      <%= link_to image_tag(@ad_xm.img_url), @ad_xm.af_link %>
      <p class="ad_info_create"><%= @ad_xm.content %></p>
    </div>
    <div>
      <h3>Titan Fx</h3>
      <%= link_to image_tag(@ad_titan.img_url), @ad_titan.af_link %>
      <p class="ad_info_create"><%= @ad_titan.content %></p>
    </div>
    <div>
      <h3>EXNESS</h3>
      <%= link_to image_tag(@ad_exness.img_url), @ad_exness.af_link %>
      <p class="ad_info_create"><%= @ad_exness.content %></p>
    </div>
  </div>
</div>
<div class="space"></div>