config/routes.rb
Rails.application.routes.draw do

  root to: 'static_page#top'
  get 'privacy_policy', to: 'static_page#privacy'
  get 'disclaimer', to: 'static_page#disclaimer'
  get 'lp', to: 'static_page#landingpage'

  devise_for :users

  resources :users, only: :update
  get '/users/:nickname' => 'users#show', as: :users_show
  get '/users/:nickname/edit' => 'users#edit', as: :users_edit
  get '/users/:nickname/record' => 'users#record', as: :users_record do
    collection do
      get 'search'
    end
  end
  get '/users/:nickname/post' => 'users#post', as: :users_post
  get '/users/:nickname/post_draft' => 'users#post_draft', as: :users_post_draft
  get '/users/:nickname/records' => 'users#records', as: :users_records
  get '/users/:nickname/search' => 'users#search', as: :users_search
  get '/users/:nickname/followings' => 'relationships#followings', as: 'followings'
  get '/users/:nickname/followers' => 'relationships#followers', as: 'followers' 
  resources :relationships, only: [:create, :destroy]

  resources :records do
    resources :comment_records
    collection do
      get 'search'
    end
  end

  resources :posts do
    resources :comment_posts
  end
  post 'posts/attach', to: 'posts#attach'
  
  resources :advertisements
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :content
    validates :category_id
    validates :keyword1
    validates :keyword2
    validates :keyword3
    validates :description
  end

  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :category_id
  end

  belongs_to :user
  has_many :comment_posts, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category, optional: true
  belongs_to :status, optional: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_ad, only: [:create, :update]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.includes(:user).where(status_id: 2).order("created_at DESC").page(params[:page]).per(12)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment_post = CommentPost.new
    @comment_posts = @post.comment_posts
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    unless @post.save
      render :new
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    unless @post.update(post_params)
      render action: :edit
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def attach
    attachment = Attachment.create! image: params[:image]
    render json: { filename: url_for(attachment.image) }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_ad
      @ad_xm = Advertisement.find(1)
      @ad_titan = Advertisement.find(4)
      @ad_exness = Advertisement.find(5)
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, :title, :category_id, :status_id, :keyword1, :keyword2, :keyword3, :description).merge(user_id: current_user.id)
    end

    def move_to_index
      unless user_signed_in? && current_user.id == @post.user_id
        redirect_to action: :show
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% content_for(:body_attributes) do %>
<% end %>

<%= javascript_pack_tag 'posts' %>

<%= form_with(model: post) do |form| %>

  <div class='error_message'>
    <%= render 'shared/error_messages', model: form.object %>
  </div>
  <div class="field">
    <p class="explain">タイトル<b class="indispensable">(必須)</b></p>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <p class="explain">キーワード<b class="indispensable">(必須)</b></p>
    <%= form.text_field :keyword1 %>
    <%= form.text_field :keyword2 %>
    <%= form.text_field :keyword3 %>
  </div>

  <div class="field">
    <p class="explain">ディスクリプション<b class="indispensable">(必須)</b></p>
    <%= form.text_field :description %>
  </div>

  <p class="explain">カテゴリーの選択をしてください<b class="indispensable">(必須)</b></p>
  <%= form.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"hour"})%>

  <div class="field">
    <p class="explain">コンテンツ内容<b class="indispensable">(必須)</b></p>
    <p class="explain">記事の書き方は<%= link_to "こちら", "https://trade-note.jp/posts/2", class: "link_word" %>に記載があります。</p>
    <%= form.text_area :content, { id: "markdown-editar"} %>
  </div>

  <p class="explain">ステータスの選択をしてください<b class="indispensable">(必須)</b></p>
  <%= form.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"hour"})%>

  <div class="actions">
    <%= form.submit "post" %>
  </div>
<% end %>

app/views/posts/create.html.erb
<div class="space"></div>
<div class="content">

  <h1>記事の作成が完了しました</h1>
  <p>
  記事を作成していただきありがとうございます。
  </p>

  <div class="container">
    <div class="btns">
      <%= link_to "記事一覧", posts_path, class: "btn" %>
      <%= link_to "記事詳細", post_path(@post.id), class: "btn" %>
      <%= link_to "マイページ", "/users/#{current_user.nickname}", class: "btn" %>
      <%= link_to "Top", "/", class: "btn" %>
    </div>
  </div>

  <h2>TradeNote運営おすすめ海外fx会社</h2>
  <div class="ad_create">
    <div>
      <h3>XM</h3>
      <%= link_to image_tag(@ad_xm.img_url), @ad_xm.af_link %>
      <p class="ad_info_create"><%= @ad_xm.content %></p>
    </div>
    <div>
      <h3>Titan Fx</h3>
      <%= link_to image_tag(@ad_titan.img_url), @ad_titan.af_link %>
      <p class="ad_info_create"><%= @ad_titan.content %></p>
    </div>
    <div>
      <h3>EXNESS</h3>
      <%= link_to image_tag(@ad_exness.img_url), @ad_exness.af_link %>
      <p class="ad_info_create"><%= @ad_exness.content %></p>
    </div>
  </div>
</div>
<div class="space"></div>

app/views/posts/edit.html.erb
<% content_for(:body_attributes) do %>
<% end %>

<% breadcrumb :post_edit %>

<div class="content">

<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path,  class: "link_word" %>

</div>

<div class="space"></div>

app/views/posts/index.html.erb
<% set_meta_tags title: '記事の一覧', description: '「自分の取引記録が最強の取引教材になるその時まで」。みんなの記事の一覧が集結！参考になる記事を探してみよう！記事を書くこともできます！' %>

<% breadcrumb :posts_index %>

<div class="content">
<h1>記事一覧</h1>
<div class="post_grid">
  <% @posts.each do |post| %>
    <%= render partial: "shared/index_post", locals: { post: post } %>
  <% end %>
</div>
  <%= paginate @posts %>

</div>
<div class="space"></div>

app/views/posts/new.html.erb
<% content_for(:body_attributes) do %>
<% end %>

<% breadcrumb :post_new %>

<div class="content">

<h1>新しい記事の作成</h1>

<%= render 'form', post: @post %>

</div>

<div class="space"></div>

app/views/posts/show.html.erb
<% if @post.category.id == 2 %>
  <% set_meta_tags title: @post.title, description: @post.description, keywords: "#{@post.category.name}, #{@post.keyword1}, #{@post.keyword2}, #{@post.keyword3}", og:{image: image_url('fx.jpg')}, twitter:{image: image_url('fx.jpg')} %>
<% elsif @post.category.id == 3 %>
  <% set_meta_tags title: @post.title, description: @post.description, keywords: "#{@post.category.name}, #{@post.keyword1}, #{@post.keyword2}, #{@post.keyword3}", og:{image: image_url('bit.jpg')}, twitter:{image: image_url('bit.jpg')} %>
<% elsif @post.category.id == 4 %>
  <% set_meta_tags title: @post.title, description: @post.description, keywords: "#{@post.category.name}, #{@post.keyword1}, #{@post.keyword2}, #{@post.keyword3}", og:{image: image_url('stock.jpg')}, twitter:{image: image_url('stock.jpg')} %>
<% elsif @post.category.id == 5 %>
  <% set_meta_tags title: @post.title, description: @post.description, keywords: "#{@post.category.name}, #{@post.keyword1}, #{@post.keyword2}, #{@post.keyword3}", og:{image: image_url('method.jpg')}, twitter:{image: image_url('method.jpg')} %>
<% elsif @post.category.id == 6 %>
  <% set_meta_tags title: @post.title, description: @post.description, keywords: "#{@post.category.name}, #{@post.keyword1}, #{@post.keyword2}, #{@post.keyword3}", og:{image: image_url('note.jpg')}, twitter:{image: image_url('note.jpg')} %>
<% elsif @post.category.id == 7 %>
  <% set_meta_tags title: @post.title, description: @post.description, keywords: "#{@post.category.name}, #{@post.keyword1}, #{@post.keyword2}, #{@post.keyword3}", og:{image: image_url('company.jpg')}, twitter:{image: image_url('company.jpg')} %>
<% elsif @post.category.id == 8 %>
  <% set_meta_tags title: @post.title, description: @post.description, keywords: "#{@post.category.name}, #{@post.keyword1}, #{@post.keyword2}, #{@post.keyword3}", og:{image: image_url('other.jpg')}, twitter:{image: image_url('other.jpg')} %>
<% end %>

<% breadcrumb :post_show %>

<div class="content">
<div class="space"></div>

<p class="title"><%= @post.title %></p>
<p class="created_by">created by <%= link_to @post.user.nickname, "/users/#{@post.user.nickname}", {class: "link_to_user"} %></p>
<%= render partial: "shared/ad_xm" %>
<div class="markdown_content">
  <%= markdown(@post.content) %>
</div>

<% if user_signed_in? && current_user.id == @post.user_id %>
  <div class="container">
    <h2>投稿者専用エリア</h2>
    <div class="btns">
      <div data-turbolinks="false" class="special_btn">
        <%= link_to '編集', edit_post_path(@post.id), class: "btn" %>
      </div>
      <div class="special_btn">
        <%= link_to '削除', post_path(@post.id), method: :delete, data: { confirm: "削除しますか？" }, class: "btn" %>
      </div>
    </div>
  </div>
<% end %>

<%= render partial: "shared/ad_xm" %>

<div class="container">
  <h2>コメント</h2>
  <% if user_signed_in? %>
    <%= form_with model: [@post, @comment_post],url: post_comment_posts_path(@post), local: false do |form| %>
      <%= form.text_area :comment, placeholder: "コメントする", rows: "2" %>
      <%= form.submit "SEND" %>
    <% end %>
  <% else %>
    <div class="btns">
      <%= link_to "新規登録してコメントする", new_user_registration_path, class: "btn" %>
      <%= link_to "ログインしてコメントする", new_user_session_path, class: "btn" %>
    </div>
  <% end %>
  <div>
    <%#<i class="fas fa-eye like-btn"></i>_<%= @record.impressions_count %>
  </div>
  
  <div class="comments">
    <h3>＜コメント一覧＞</h3>
    <div id="comments__area">
      <%= render partial: 'comment_posts/index', locals: { comments: @comment_posts } %>
    </div>
  </div>
</div>

</div>

<div class="space"></div>

app/views/posts/update.html.erb
<div class="space"></div>
<div class="content">

  <h1>記事の編集が完了しました</h1>
  <p>
  記事を編集していただきありがとうございます。
  </p>

  <div class="container">
    <div class="btns">
      <%= link_to "記事一覧", posts_path, class: "btn" %>
      <%= link_to "記事詳細", post_path(@post.id), class: "btn" %>
      <%= link_to "マイページ", "/users/#{current_user.nickname}", class: "btn" %>
      <%= link_to "Top", "/", class: "btn" %>
    </div>
  </div>

  <h2>TradeNote運営おすすめ海外fx会社</h2>
  <div class="ad_create">
    <div>
      <h3>XM</h3>
      <%= link_to image_tag(@ad_xm.img_url), @ad_xm.af_link %>
      <p class="ad_info_create"><%= @ad_xm.content %></p>
    </div>
    <div>
      <h3>Titan Fx</h3>
      <%= link_to image_tag(@ad_titan.img_url), @ad_titan.af_link %>
      <p class="ad_info_create"><%= @ad_titan.content %></p>
    </div>
    <div>
      <h3>EXNESS</h3>
      <%= link_to image_tag(@ad_exness.img_url), @ad_exness.af_link %>
      <p class="ad_info_create"><%= @ad_exness.content %></p>
    </div>
  </div>
</div>
<div class="space"></div>