config/routes.rb
Rails.application.routes.draw do

  root to: 'static_page#top'
  get 'privacy_policy', to: 'static_page#privacy'
  get 'disclaimer', to: 'static_page#disclaimer'
  get 'lp', to: 'static_page#landingpage'

  devise_for :users

  resources :users, only: :update
  get '/users/:nickname' => 'users#show', as: :users_show
  get '/users/:nickname/edit' => 'users#edit', as: :users_edit
  get '/users/:nickname/record' => 'users#record', as: :users_record do
    collection do
      get 'search'
    end
  end
  get '/users/:nickname/post' => 'users#post', as: :users_post
  get '/users/:nickname/post_draft' => 'users#post_draft', as: :users_post_draft
  get '/users/:nickname/records' => 'users#records', as: :users_records
  get '/users/:nickname/search' => 'users#search', as: :users_search
  get '/users/:nickname/followings' => 'relationships#followings', as: 'followings'
  get '/users/:nickname/followers' => 'relationships#followers', as: 'followers' 
  resources :relationships, only: [:create, :destroy]

  resources :records do
    resources :comment_records
    collection do
      get 'search'
    end
  end

  resources :posts do
    resources :comment_posts
  end
  post 'posts/attach', to: 'posts#attach'
  
  resources :advertisements
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag('logo.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= display_meta_tags(default_meta_tags) %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6951652029566360"
     crossorigin="anonymous"></script>
  </head>

  <body>
  <%= breadcrumbs separator: " &rsaquo; " %> 
  <% if content_for?(:body_attributes) %>
    <%= yield(:body_attributes) %>
  <% end %>
  <header id="header">
      
    <div class="heading" id="heading_id">
      <%= image_tag 'logo.png', class: "title_logo" %>
      <%= link_to "Trade-Note", "/" %>
    </div>
    
    <div class="none">
      <%# if user_signed_in? %>
        <div class="current_user">
          <%#user :   <%= link_to current_user.name, "/users/#{current_user.id}", class: 'user_name' %>
        </div>
      <%# else %>
        <div class="current_user">
          
        </div>
      <%# end %>
    </div>

    <nav id="nav_bar">
      <div class="space"></div>
      <ul class="navi_list">  
        <li class="navi"><%= link_to 'Top', root_path  %></li>
        <li class="navi"><%= link_to 'TradeNote', records_path %></li>
        <li class="navi"><%= link_to '記事', posts_path %></li>
      </ul>
      <ul class="navi_log">
        <% if user_signed_in? %>
          <li class="navi"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <li class="navi"><%= link_to 'マイページ', "/users/#{current_user.nickname}" %></li>
          <li class="navi"><%= link_to '新規TradeNoteの作成', new_record_path %></li>
          <div data-turbolinks="false">
          <li class="navi"><%= link_to '新規記事の作成', new_post_path %></li>
          <li class="navi"><%= link_to '記事の書き方', "https://trade-note.jp/posts/2" %></li>
          </div>
        <% else %>
          <li class="navi"><%= link_to 'ログイン', new_user_session_path %></li>
          <li class="navi"><%= link_to '新規登録', new_user_registration_path %></li>
        <% end %>
      </ul>
      
      <ul class="navi_pages">
        <% if user_signed_in? %>
          <li class="navi">
          <%= link_to "https://liff.line.me/1645278921-kWRPP32q?accountId=662tugjz#mst_challenge=xQINvbfNZG-ib2wvs4A5jFQfrDVKLss9ZWCHLhHlyvk" do %>
            お問い合わせ<i class="fab fa-line line-btn"></i>
          <% end %>
        </li>
        <% end %>
        <li class="navi">
        <%= link_to "https://twitter.com/Trade__Note" do %>
          お知らせ<i class="fab fa-twitter-square twitter-btn"></i>
        <% end %>
        </li>
      </ul>
    </nav>

    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>

    <div id="mask"></div>
  </header>

    <%= yield %>
    
  <% unless current_page?("/LP") %>
    <%= render partial: "shared/ad_xm" %>
  <% end %>

  <div class="space"></div>

  <% unless user_signed_in? || current_page?("/LP") %>
    <div class="content">
      <h1>トレードノートを作ろう</h1>

      <p class="catch">自分のトレードノートが世界最高の取引教材となるその時まで</p>

      <div class="show_content">

        <h2>トレードノートから取引を分析</h2>
        
          <p class="highlight">新規登録ログインしてトレードノートを作って分析</p>
          <p>
          自身の取引を記録することでデータを作りグラフ化していきます。<br>
          自分の取引を客観的に見て取引精度をあげ、資産を増やしていきましょう！
          </p>
          <ul class="list">
            <li>資産推移のグラフ化</li>
            <%= image_tag "graph.png", class: "graph_img" %>
            <li>通貨ペア別の勝率とPF</li>
            <%= image_tag "pf.png", class: "graph_img" %>
            <li>改善ポイントの明確化</li>
            <%= image_tag "result.png", class: "graph_img" %>
          </ul>
          それぞれ、全体の情報と今月分のデータがわかります。
        
        <div class="space"></div>
        
        <div class="btns">
          <%= link_to "新規登録してトレードノートを作る", new_user_registration_path, class: "btn" %>
          <%= link_to "ログインしてトレードノートを作る", new_user_session_path, class: "btn" %>
        </div>

        <h2>トレードノートを公開するメリット</h2>
          <ul class="list">
            <li>ポジポジ病が減る</li>
            <li>取引ルールが明確になる</li>
            <li>取引ルールを守れるようになる</li>
            <li>自身の取引に対する理解が深まる</li>
            <li>取引ルールのブラッシュアップ</li>
            <li>取引記録に対するフィードバック</li>
            <li>他トレーダーの記録で勉強できる</li>
          </ul>
      </div>

      <h1>記事を書こう！</h1>

      <div class="show_content">

        <p class="highlight">新規登録ログインして記事を書いて収益化</p>
        <h2>自分の書いた記事にアフィリエイトリンクを貼ろう！</h2>
        <p>
        投資に関する内容の記事を投稿することができます。またその記事内にアフィリエイトリンクを貼り付けて記事の収益化ができます。
        </p>
        <ul class="list">
          <li>簡単に記事が書ける</li>
          <li>投資関連のアフィリエイトリンクの貼り付けができる</li>
          <li>記事を書くことで考え方を整理することができる</li>
        </ul>
        <b>注意: 記事作成、アフィリエイトリンクの貼り付けにはルールが設けられています。詳しくは<%= link_to "こちら", "https://trade-note.jp/posts/2", class: "link_word" %>をご覧ください。</b>

      </div>

      <div class="space"></div>
        
      <div class="btns">
        <%= link_to "新規登録して記事を作る", new_user_registration_path, class: "btn" %>
        <%= link_to "ログインして記事を作る", new_user_session_path, class: "btn" %>
      </div>
    </div>
  <% end %>

  <div class="space"></div>

  <footer id="footer">
    <div class="space"></div>
    <div class="footer_links">
      <div class="footer_link">
        <%= link_to 'プライバシーポリシー', privacy_policy_path, class: "link_word" %>
      </div>
      <div class="footer_link">
        <%= link_to '免責事項', disclaimer_path, class: "link_word" %>
      </div>
    </div>
    <div class="risk_warning">
      <p class="footer_word">
      Trade-Noteについて：<br>
      Trade-Noteはfx、仮想通貨などの金融商品の取引記録・取引手法などを記録・公開して分析することで、自分自身の取引を見つめ直すことができることを目的としサービス提供を開始いたしました。また、第三者の取引記録・分析結果を参考にすることができるため、投資家判断の参考となる情報共有も目的としています。<br>
      今後も、ユーザー様のサポートのため新機能の追加などを行ってまいります。
      </P>
    </div>
    <div class="risk_warning">
      <p class="footer_word">
      リスクの警告：<br>
      FX取引には投資元金を失う非常に高いリスクが伴います。取引に利用されるレバレッジは有利にも不利にも作用する可能性があります。具体的には、オープンされたポジションと逆の値動きがある場合には取引の結果投資元本の全てを失う可能性があり、必ずしも全てのお客様に適した金融商品であると確約することはできません。したがって、投資は損失を許容できる範囲内にとどめることをお願いします。取引を始める前に、リスクについて、リスク警告を十分にご理解の上、ご自身の経験についてよく考慮してください。
      </P>
    </div>
    <div class="cantainer">
      <p class="copyright">Copyright Trade-Note allright reserved</p>
    </div>
    <div class="space"></div>
  </footer>

<%#
  <i class="far fa-times-circle" id="none"></i>
%>
<% unless current_page?(new_user_session_path) || current_page?(new_user_registration_path) %>
  <div class="new">
    <div class="new_icon">
      <i class="fas fa-file-medical"></i>
    </div>
    <div class="new_word">
      <p>トレードノートを作る</p>
    </div>
    <a class="link" href="/records/new"></a>
  </div>
<% end %>

  <div class="space"></div>
  <div class="space"></div>

  </body>
</html>